project6: dhrube2Proj6.o Islands.o
	g++ -o project6 dhrube2Proj6.o Islands.o

dhrube2Proj6.o: dhrube2Proj6.cpp Island.h
	g++ -c dhrube2Proj6.cpp

Islands.o: Islands.cpp Island.h
	g++ -c Islands.cpp

clean:
	rm dhrube2Proj6.o Islands.o project6
